import flet as ft

TEXTS = {
    'en': {
        "app_title": "Building SCADA", "login_title": "Building SCADA - Login",
        "dashboard_title": "Building SCADA - Dashboard", "config_title": "Building SCADA - Config",
        "login": "Login", "username": "Username", "password": "Password",
        "invalid_credentials": "Invalid username or password!", "plc_connected": "PLC Connected",
        "plc_disconnected": "PLC Disconnected", "dashboard": "Dashboard", "config_panel": "Config Panel",
        "logout": "Logout", "floor_0": "Floor 0", "floor_1": "Floor 1", "floor_2": "Floor 2",
        "parking_lot": "Parking Lot", "quick_controls": "Quick Controls", "alerts": "Alerts",
        "no_alerts": "No active alerts.", "lobby": "Lobby", "office_1": "Office 1", "office_2": "Office 2",
        "corridor_1": "Corridor 1", "office_3": "Office 3", "corridor_2": "Corridor 2",
        "movement_detected": "MOVEMENT DETECTED", "no_movement": "No movement",
        "smoke_detected": "SMOKE DETECTED", "no_smoke": "No smoke", "light_on": "LIGHT ON",
        "light_off": "Light off", "door_open": "DOOR OPEN", "door_closed_tooltip": "Door closed",
        "rfid_accepted": "RFID ACCEPTED", "rfid_rejected": "RFID REJECTED", "no_card": "No card",
        "security_active": "SECURITY ACTIVE",
        "security_inactive": "Security inactive", "heating_on": "HEATING ON", "heating_off": "Heating off",
        "cooling_on": "COOLING ON", "cooling_off": "Cooling off",
        "object_in_front": "OBJECT IN FRONT OF GATE", "no_object": "No object",
        "opening_gate": "OPENING GATE", "gate_not_opening": "Gate not opening",
        "gate_not_closed": "GATE NOT CLOSED", "gate_closed_tooltip": "Gate closed",
        "closing_gate": "CLOSING GATE", "gate_not_closing": "Gate not closing",
        "button_pressed_inside": "BUTTON PRESSED INSIDE",
        "button_not_pressed_inside": "Button not pressed inside",
        "rfid_accepted_outside": "RFID ACCEPTED OUTSIDE", "no_card_outside": "No card outside",
        "keep_lobby_door_open": "Keep Lobby door open", "keep_parking_open": "Keep Parking lot open",
        "keep_parking_closed": "Keep Parking lot closed", "set_parking_spots": "Set Parking spots taken:",
        "plc_config": "PLC Configuration", "db_management": "Database Management",
        "work_schedule": "Work Schedule", "mo": "Mo", "tu": "Tu", "we": "We", "th": "Th", "fr": "Fr",
        "sa": "Sa", "su": "Su", "work_hours_start": "Work Hours Start (0-24)",
        "work_hours_end": "Work Hours End (0-24)", "heating_cooling": "Heating & Cooling",
        "enable_heating_off_days": "Enable on non-work days", "cold_months_begin": "Cold Months Begin",
        "cold_months_end": "Cold Months End", "desired_work_temp": "Work Day Temperature (°C)",
        "work_temp_tolerance": "Tolerance (°C)", "desired_non_work_temp": "Non-Work Day Temperature (°C)",
        "config_parking_lot": "Parking Lot",
        "num_spots": "Number of Spots", "max_spots": "Theoretical Maximum Spots",
        "num_spots_taken": "Number of Spots Taken", "lights_control": "Lights Control",
        "threshold_lux": "Threshold (lux)", "tolerance_lux": "Tolerance (lux)", "config_lobby": "Lobby",
        "enable_auto_lights_lobby": "Enable Auto Lights Lobby", "keep_on_dark": "on when dark",
        "activate_on_movement": "on movement", "config_building": "Building",
        "enable_auto_lights_building": "Enable Auto Lights Building", "system_testing": "System Testing",
        "enable_sim_io": "Enable Simulated I/O", "test_fire": "Test Fire System",
        "test_security": "Test Security System", "submit_changes": "Submit Changes",
        "changes_submitted": "PLC Changes Submitted!", "sql_query": "SQL Query",
        "exec_query": "Execute Query", "view_log": "View Log", "view_people": "View People",
        "view_cards": "View Cards", "add_person": "Add Person", "add_card": "Add Card",
        "remove_card": "Remove Card", "remove_person": "Remove Person",
        "db_results": "Query Results", "error_executing_query": "Error:",
        "no_results": "No results to display.", 'view_access': "View Access", 'add_access': "Add Access",
        'remove_access': "Remove Access",
        'add_person_fname': "First Name *", 'add_person_mname': "Middle Name", 'add_person_lname': "Last Name *",
        'add_card_number': "Card Number (10 digits) *", 'add_card_person_id': "Person ID *",
        'add_access_card_id': "Card ID *", 'add_access_location_id': "Location ID *",
        'remove_person_id': "Person ID to delete *", 'remove_card_id': "Card ID to delete *",
        'remove_access_id': "Access ID to delete *", 'form_submit': "Submit",
        'form_error_required': "Field '{field_name}' is required.",
        'add_card_error_format': "Card number must be exactly 10 digits.",
        'wd_only_lights': "Work days only", 'measured_light': "Measured Light (lux):"
    },
    'bg': {
        "app_title": "SCADA на Сграда", "login_title": "SCADA - Вход",
        "dashboard_title": "SCADA - Контролно табло", "config_title": "SCADA - Конфигурация",
        "login": "Вход", "username": "Потребител", "password": "Парола",
        "invalid_credentials": "Грешно потребителско име или парола!", "plc_connected": "ПЛК свързан",
        "plc_disconnected": "ПЛК не е свързан", "dashboard": "Контролно табло",
        "config_panel": "Конфигурационен панел", "logout": "Изход", "floor_0": "Етаж 0",
        "floor_1": "Етаж 1", "floor_2": "Етаж 2", "parking_lot": "Паркинг",
        "quick_controls": "Управление", "alerts": "Аларми", "no_alerts": "Няма активни аларми.",
        "lobby": "Фоайе", "office_1": "Офис 1", "office_2": "Офис 2", "corridor_1": "Коридор 1",
        "office_3": "Офис 3", "corridor_2": "Коридор 2", "movement_detected": "ЗАСЕЧЕНО ДВИЖЕНИЕ",
        "no_movement": "Няма движение", "smoke_detected": "ЗАСЕЧЕН ДИМ", "no_smoke": "Няма дим",
        "light_on": "СВЕТЛИНА ВКЛ.", "light_off": "Светлина изкл.", "door_open": "ВРАТА ОТВОРЕНА",
        "door_closed_tooltip": "Врата затворена", "rfid_accepted": "RFID КОД Е ПРИЕТ",
        "rfid_rejected": "RFID КОД Е ОТХВЪРЛЕН",
        "no_card": "Няма карта", "security_active": "ОХР. СИСТ. Е АКТИВНА",
        "security_inactive": "Охр. сист. е изключена", "heating_on": "ОТОПЛЕНИЕ ВКЛ.",
        "heating_off": "Отопление изкл.", "cooling_on": "ОХЛАЖДАНЕ ВКЛ.", "cooling_off": "Охлаждане изкл.",
        "object_in_front": "ОБЕКТ ПРЕД ВРАТАТА", "no_object": "Няма обект",
        "opening_gate": "ВРАТАТА СЕ ОТВАРЯ", "gate_not_opening": "Вратата не се отваря",
        "gate_not_closed": "ВРАТАТА НЕ Е ЗАТВОРЕНА", "gate_closed_tooltip": "Вратата е затворена",
        "closing_gate": "ВРАТАТА СЕ ЗАТВАРЯ", "gate_not_closing": "Вратата не се затваря",
        "button_pressed_inside": "НАТИСНАТ БУТОН ВЪТРЕ",
        "button_not_pressed_inside": "Бутонът не е натиснат вътре",
        "rfid_accepted_outside": "RFID ПРИЕТ ОТВЪН", "no_card_outside": "Няма карта отвън",
        "keep_lobby_door_open": "Отключи фоайето", "keep_parking_open": "Отвори паркинга",
        "keep_parking_closed": "Затвори паркинга", "set_parking_spots": "Задай заети места:",
        "plc_config": "Конфигурация на ПЛК", "db_management": "Управление на база данни",
        "work_schedule": "Работен график", "mo": "Пн", "tu": "Вт", "we": "Ср", "th": "Чт", "fr": "Пт",
        "sa": "Сб", "su": "Нд", "work_hours_start": "Начало на раб. време (0-24)",
        "work_hours_end": "Край на раб. време (0-24)", "heating_cooling": "Отопление и охлаждане",
        "enable_heating_off_days": "Активирай в неработни дни", "cold_months_begin": "Начало на студени месеци",
        "cold_months_end": "Край на студени месеци", "desired_work_temp": "Желана темп. раб. дни (°C)",
        "work_temp_tolerance": "Толеранс на темп. (°C)",
        "desired_non_work_temp": "Желана темп. нераб. дни (°C)",
        "config_parking_lot": "Паркинг",
        "num_spots": "Брой места", "max_spots": "Теоретичен макс. места",
        "num_spots_taken": "Брой заети места", "lights_control": "Контрол на осветление",
        "threshold_lux": "Праг (lux)", "tolerance_lux": "Толеранс (lux)", "config_lobby": "Фоайе",
        "enable_auto_lights_lobby": "Автоматично осветление фоайе", "keep_on_dark": "при тъмнина",
        "activate_on_movement": "при движение", "config_building": "Сграда",
        "enable_auto_lights_building": "Автоматично осветление сграда",
        "system_testing": "Тестване на системата", "enable_sim_io": "Симулирани I/O",
        "test_fire": "Тест на пожарна система", "test_security": "Тест на охранителна система",
        "submit_changes": "Запази промените", "changes_submitted": "Промените в ПЛК са изпратени!",
        "sql_query": "SQL Заявка", "exec_query": "Изпълни заявка", "view_log": "Виж събития",
        "view_people": "Виж хора", "view_cards": "Виж карти", "add_person": "Добави човек",
        "add_card": "Добави карта", "remove_card": "Премахни карта", "remove_person": "Премахни човек",
        "db_results": "Резултати от заявката", "error_executing_query": "Грешка:",
        "no_results": "Няма резултати за показване.", 'view_access': "Виж достъпи", 'add_access': "Добави достъп",
        'remove_access': "Премахни достъп",
        'add_person_fname': "Първо име *", 'add_person_mname': "Презиме", 'add_person_lname': "Фамилия *",
        'add_card_number': "Номер на карта (10 цифри) *", 'add_card_person_id': "ID на човек *",
        'add_access_card_id': "ID на карта *", 'add_access_location_id': "ID на локация *",
        'remove_person_id': "ID на човек за изтриване *", 'remove_card_id': "ID на карта за изтриване *",
        'remove_access_id': "ID на достъп за изтриване *", 'form_submit': "Изпрати",
        'form_error_required': "Полето '{field_name}' е задължително.",
        'add_card_error_format': "Номерът на картата трябва да е точно 10 цифри.",
        'wd_only_lights': "Само в работни дни", 'measured_light': "Измерена светлина (lux):"
    }
}

ALERT_TEXTS = {
    'en': {
        'emergency_txt': "EMERGENCY", 'fire_sprinklers_on_txt': "FIRE SPRINKLERS ON",
        'call_fire_dept_txt': "CALLING FIRE DEPARTMENT", 'call_security_txt': "CALLING SECURITY",
        'err_cold_month_config_txt': "ERROR COLD MONTH CONFIG", 'err_work_day_config_txt': "ERROR WORK DAY CONFIG",
        'err_temp_config_txt': "ERROR TEMPERATURE CONFIG", 'err_pspot_config_txt': "ERROR PARKING SPOT CONFIG",
        'err_pgate_force_txt': "ERROR OPEN AND CLOSE", 'err_light_config_txt': "ERROR LIGHT CONFIG",
        'warn_pspot_miscount_txt': "WARNING PARK. SPOT MISCOUNT",
        'warn_pgate_open_txt': "WARNING PARK. LOT OPEN", 'warn_fire_det_txt': "WARNING FIRE DETECTED",
        'warn_auto_security_impossible_txt': "WARNING SECURITY INACTIVE",
        'warn_config_altered_txt': "WARNING CONFIG ALTERED",
    },
    'bg': {
        'emergency_txt': "ОПАСНОСТ!", 'fire_sprinklers_on_txt': "ПОЖАРНИ ПРЪСКАЧКИ ВКЛ.",
        'call_fire_dept_txt': "ОБАЖДАНЕ НА ПОЖАРНА", 'call_security_txt': "ОБАЖДАНЕ НА ОХРАНА",
        'err_cold_month_config_txt': "ГРЕШКА: КОНФ. СТУДЕНИ МЕСЕЦИ",
        'err_work_day_config_txt': "ГРЕШКА: КОНФ. РАБОТНИ ДНИ",
        'err_temp_config_txt': "ГРЕШКА: КОНФ.ТЕМПЕРАТУРА ",
        'err_pspot_config_txt': "ГРЕШКА: КОНФ. ПАРКОМЕСТА",
        'err_pgate_force_txt': "ГРЕШКА: ОТВ. И ЗАТВ.",
        'err_light_config_txt': "ГРЕШКА: КОНФ. ОСВЕТЛЕНИЕ",
        'warn_pspot_miscount_txt': "ВНИМАНИЕ: НЕЯСЕН БРОЙ СВОБ. МЕСТА",
        'warn_pgate_open_txt': "ВНИМАНИЕ: ОТВОРЕН ПАРКИНГ",
        'warn_fire_det_txt': "ВНИМАНИЕ: ЗАСЕЧЕН ПОЖАР",
        'warn_auto_security_impossible_txt': "ВНИМАНИЕ: ОХР. СИСТ. НЕАКТ.",
        'warn_config_altered_txt': "ВНИМАНИЕ: ПРОМЕНЕНА КОНФИГ.",
    }
}

USERS = {
    "operator": {"password": "op123", "role": "operator"},
    "admin": {"password": "Admn1!", "role": "administrator"},
    "": {"password": "", "role": "administrator"}
}

ALERT_DEFS = [
    (25, 'emergency', 'emergency_txt', ft.Icons.WARNING, ft.Colors.RED_ACCENT_400),
    (24, 'fire_sprinklers_on', 'fire_sprinklers_on_txt', ft.Icons.FIRE_EXTINGUISHER, ft.Colors.BLUE_ACCENT),
    (23, 'call_fire_dept', 'call_fire_dept_txt', ft.Icons.FIRE_TRUCK, ft.Colors.RED_ACCENT_400),
    (22, 'call_security', 'call_security_txt', ft.Icons.SECURITY, ft.Colors.BLUE_ACCENT),
    (11, 'err_cold_month_config', 'err_cold_month_config_txt', ft.Icons.WARNING, ft.Colors.ORANGE_600),
    (10, 'err_work_day_config', 'err_work_day_config_txt', ft.Icons.WARNING, ft.Colors.ORANGE_600),
    (9, 'err_temp_config', 'err_temp_config_txt', ft.Icons.WARNING, ft.Colors.ORANGE_600),
    (8, 'err_pspot_config', 'err_pspot_config_txt', ft.Icons.WARNING, ft.Colors.ORANGE_600),
    (7, 'err_pgate_force', 'err_pgate_force_txt', ft.Icons.WARNING, ft.Colors.ORANGE_600),
    (6, 'err_light_config', 'err_light_config_txt', ft.Icons.WARNING, ft.Colors.ORANGE_600),
    (5, 'warn_pspot_miscount', 'warn_pspot_miscount_txt', ft.Icons.WARNING_AMBER, ft.Colors.ORANGE),
    (4, 'warn_pgate_open', 'warn_pgate_open_txt', ft.Icons.WARNING_AMBER, ft.Colors.ORANGE),
    (20, 'warn_fire_det', 'warn_fire_det_txt', ft.Icons.WARNING_AMBER, ft.Colors.RED_ACCENT_200),
    (2, 'warn_auto_security_impossible', 'warn_auto_security_impossible_txt', ft.Icons.WARNING_AMBER, ft.Colors.ORANGE),
]
